#!/usr/bin/env python3
"""Author the LLM prose layer on the 7 OKF skeleton pages.

Each page's prose is injected between the `<!-- loom:prose-start -->` and
`<!-- loom:prose-end -->` sentinels that `loom wiki --okf` emits. The skeleton
(frontmatter + graph-derived body) is byte-checked separately by `--check`;
this script only touches the prose region.
"""
import os

ROOT = "/Users/laptopdp/Developer/damarpanuluh/loom"
WIKI = os.path.join(ROOT, "loom.wiki")
PROSE_START = "<!-- loom:prose-start -->"
PROSE_END = "<!-- loom:prose-end -->"

SALIENT = {
    "6faa01a5-920a-4231-b840-f4c2057d149b": "loom: living intent graph CLI",
    "a1a8eb10-bc4c-43d7-a4ec-b7d1fb8d26ae": "CLI surface and dispatch",
    "988027a3-d33a-40c8-8f32-c5140b0d1937": "graph-write command handlers",
    "bb8ee237-2d84-46ee-b254-c8bc39c16fc1": "dual-mode output",
    "f2995090-ba95-48d3-bb6d-21b4044c32dc": "self-teaching surface",
    "01783338-7f02-4f4b-8d15-5f396ef7d47d": "SQLite graph persistence",
    "c2f6bca0-2ccd-48b7-af47-1a74fba61441": "SQLite-backed graph persistence migration",
    "29288a6c-3f0b-4762-a34d-ad4a714b5390": "endpoint-constrained edge storage",
    "29799603-3704-4dfa-9ba4-387a7c1942f8": "sync flag engine",
    "47c9182c-f7a8-4a50-9281-6d05507e646c": "priority-scored work queues",
    "ab4ac603-a14d-4ae4-b68b-a4bf9dce0cb2": "completeness and integrity checking",
    "c61f66f5-a396-4494-9b48-c00d5203bcb3": "multi-hop audit layer",
    "e2d64ed4-b10f-48fd-995b-f533a6250a18": "snapshot analysis and annotation helpers",
    "382c288a-4846-46f6-93be-eb9e1f40faf3": "repo introspection",
    "ea9c7e3e-9f95-4d58-ade9-d771fcf50cc3": "multi-language static analysis coverage",
    "dda91659-329a-479e-9d33-42a41b5fa9b1": "source corpus coverage",
    "20bf582e-df31-4f96-8b37-6171c38e3478": "role lanes and evidence gates",
    "32b42fd0-6b6c-46a6-a9a8-97be595bddf3": "hypothesis plane",
    "fcf2f089-6dbe-46f0-8296-d50512420ff8": "external interface surface plane",
    "4c752ad2-e332-4148-87e2-88340991e2a5": "saga consumer plane",
    "c6b2b5d9-387a-4fa3-936d-e4e780021067": "UI/UX visual-register seed flow",
    "e21d2c64-f9fa-46c0-aaec-1985efbf8152": "intent-spectrum seed-flow guidance",
}


def link(intent_id):
    return f"[{SALIENT[intent_id]}](intent:{intent_id})"


def file_link(path):
    return f"[`{path}`](../{path})"


PROSE = {}

PROSE["index.md"] = f"""\
## What loom is

loom is a living intent graph for a codebase. Every responsibility the code
fulfils is an intent — a named, criteriated, lifecycle-tracked node — and
every relationship between responsibilities (decomposition, coupling,
governance, validation) is a typed edge. The system intent
{link('6faa01a5-920a-4231-b840-f4c2057d149b')} is the root: a CLI that keeps
the graph and the code in lockstep so the graph is always a faithful model of
what the code actually does.

## How to read this wiki

This wiki is two layers in one artifact. The deterministic **skeleton** above
this prose block is generated by `loom wiki --okf` — frontmatter plus
graph-derived sections that are byte-identical for a given graph, so
`loom wiki --okf --check` guards freshness the way `loom export --check` does.
The **prose** you are reading now is the LLM-authored narrative layer hung on
that skeleton: it teaches *how the system fits together, where to start, and
how a request travels* — the comprehension the skeleton's flat listings cannot
convey on their own.

The prose is falsifiable, not trusted. Three mechanical gates certify it:
**coverage** (every salient intent is cited by at least one page), **freshness**
(every cited codefile's content-hash matches the hash registered in the graph,
so prose about stale code is flagged), and **consistency** (every cross-link
resolves to a real graph node). Prose **quality** — does this actually teach a
newcomer? — stays human-gated and is never machine-green. Run
`loom wiki --okf --prose-check` to certify the mechanical gates.

## Where to start

- New to the codebase? Read [architecture.md](architecture.md) for the layered
  shape, then [components.md](components.md) for the responsibility map.
- Writing a command? [components.md](components.md) names the components; the
  {link('f2995090-ba95-48d3-bb6d-21b4044c32dc')} is the guide that tells you
  which lane owns the work.
- On-call for a failure? [quality.md](quality.md) is the quality axis;
  [decisions.md](decisions.md) carries the recorded rulings that explain why
  the code looks the way it does.
- Reviewing a hypothesis? [flows.md](flows.md) traces a request end-to-end,
  including the {link('32b42fd0-6b6c-46a6-a9a8-97be595bddf3')} where
  speculation is proven before it touches coverage.

## Coverage ledger

Every salient intent (system, component, and user_visible) must be cited by at
least one prose page. The ledger is the output of the coverage gate; a green
`loom wiki --okf --prose-check` means every name below is anchored to prose.

- {link('6faa01a5-920a-4231-b840-f4c2057d149b')} — the root system intent
- {link('a1a8eb10-bc4c-43d7-a4ec-b7d1fb8d26ae')} — the entry point
- {link('f2995090-ba95-48d3-bb6d-21b4044c32dc')} — the teaching axis
- {link('01783338-7f02-4f4b-8d15-5f396ef7d47d')} — the storage axis
- {link('47c9182c-f7a8-4a50-9281-6d05507e646c')} — the work axis
- {link('ab4ac603-a14d-4ae4-b68b-a4bf9dce0cb2')} — the integrity axis
- {link('20bf582e-df31-4f96-8b37-6171c38e3478')} — the governance axis
- {link('32b42fd0-6b6c-46a6-a9a8-97be595bddf3')} — the speculation axis
- {link('fcf2f089-6dbe-46f0-8296-d50512420ff8')} — the external surface axis

The remaining salient intents are cited from their topical pages
([components.md](components.md), [quality.md](quality.md), [flows.md](flows.md),
[glossary.md](glossary.md)).
"""

PROSE["architecture.md"] = f"""\
## The layered shape

loom is a single binary built from four concentric layers, each modelled as a
family of component intents in the graph. Reading the layers outside-in is the
fastest way to orient: every request enters at the CLI rim, is dispatched to a
command handler, reads or writes through the persistence core, and is certified
by the audit + integrity layer that wraps the core.

### Rim — the CLI surface

The outermost layer is the {link('a1a8eb10-bc4c-43d7-a4ec-b7d1fb8d26ae')}:
clap-derive command definitions in {file_link("src/cli.rs")} and the dispatch
table in {file_link("src/commands/mod.rs")}. A bare `loom` invocation does not
error — it prints an orientation that points at the
{link('f2995090-ba95-48d3-bb6d-21b4044c32dc')}, so an agent that knows nothing
can find its footing. Every command renders both human-readable text and
structured JSON via the {link('bb8ee237-2d84-46ee-b254-c8bc39c16fc1')}, so the
same surface serves a person at a terminal and a script piping `--json` into
the next step.

### Spokes — the command handlers

Behind the dispatch table are the
{link('988027a3-d33a-40c8-8f32-c5140b0d1937')}: one module per noun (`intent`,
`edge`, `codefile`, `validation`, `note`, `rule`, `ignore`, `export`/`import`),
each lane-gated so a builder cannot record a verdict and a validator cannot
seed an intent. The handlers are thin — they parse CLI args, call into the
persistence + analysis core, and render — so the policy lives in the graph,
not in the handlers.

### Core — SQLite graph persistence

The persistence core is the {link('01783338-7f02-4f4b-8d15-5f396ef7d47d')}:
an embedded SQLite store behind typed command/repository APIs in
{file_link("src/db/sqlite.rs")}. The schema vocabulary is declared in Rust
({file_link("src/db/schema.rs")}); the physical tables and constraints live in
SQLite. Edges are {link('29288a6c-3f0b-4762-a34d-ad4a714b5390')} — keyed by
endpoint ids with derived stable edge ids and SQLite uniqueness/foreign-key
constraints, not stored edge uuids — so an edge is identity-stable across
re-import. The migration from the legacy live-graph backend is itself an
intent, {link('c2f6bca0-2ccd-48b7-af47-1a74fba61441')}, proven by the parity
harness in {file_link("tests/sqlite_regression.rs")}.

### Wrap — audit, integrity, and work selection

Wrapping the core are three cross-cutting components. The
{link('ab4ac603-a14d-4ae4-b68b-a4bf9dce0cb2')} runs `loom doctor`,
`loom smells`, and `loom coverage` — the deterministic checks that catch a
graph drifting from the code. The
{link('c61f66f5-a396-4494-9b48-c00d5203bcb3')}
({file_link("src/db/queries/snapshot.rs")}) is the read-side that serves
multi-hop graph computations without re-scanning. The
{link('47c9182c-f7a8-4a50-9281-6d05507e646c')} is the write-side that ranks
the next item for every lane — `loom next --mode <lane>` is the single entry
point for "what do I work on now?".

### Cross-cutting — sync, analysis, teaching

Three more components cut across all layers. The
{link('29799603-3704-4dfa-9ba4-387a7c1942f8')} is the change detector:
`loom sync` re-hashes touched files and flips only the one-hop RELATES_TO
neighbours of affected intents to `needs_reverification`, with a decaying
ripple beyond. The {link('382c288a-4846-46f6-93be-eb9e1f40faf3')} and
{link('ea9c7e3e-9f95-4d58-ade9-d771fcf50cc3')} are the multi-language
static-analysis plane that extracts imports, declarations, and layout signals
so coverage and coupling signals are language-aware. The
{link('e2d64ed4-b10f-48fd-995b-f533a6250a18')} backs `loom find`,
`loom smells`, and `loom coverage` against the shared snapshot.

## How a request travels

A `loom <noun> <verb>` invocation resolves its target graph via `--graph` flag
> `LOOM_GRAPH` env > cwd, then dispatches to the noun's handler module, which
calls a typed query in {file_link("src/db/queries/")} and renders through
{file_link("src/output.rs")}. The {link('20bf582e-df31-4f96-8b37-6171c38e3478')}
gates every transition — a builder records a verdict, a validator seeds a rule
— so the graph is append-only-auditable, not free-form. See
[flows.md](flows.md) for the end-to-end trace of a representative request.
"""

PROSE["components.md"] = f"""\
## The responsibility map

Each component intent owns a family of feature intents and is grounded in a
concrete set of source files. This page is the index from a component name to
the files that implement it; the skeleton above lists the deterministic
projection, and the prose below explains the *why* behind each component.

### CLI and dispatch

{link('a1a8eb10-bc4c-43d7-a4ec-b7d1fb8d26ae')} — clap-derive definitions in
{file_link("src/cli.rs")} plus the dispatch table in
{file_link("src/commands/mod.rs")}. Owns argument parsing, the orientation
printout for bare `loom`, and the synonym/typo teacher for unrecognized verbs.

{link('988027a3-d33a-40c8-8f32-c5140b0d1937')} — the mutating command modules
under {file_link("src/commands/")}. Each noun has one file (`intent.rs`,
`edge.rs`, `codefile.rs`, `validation.rs`, `note.rs`, `rule.rs`, `ignore.rs`);
every transition is lane-gated by the
{link('20bf582e-df31-4f96-8b37-6171c38e3478')}.

{link('bb8ee237-2d84-46ee-b254-c8bc39c16fc1')} — every handler renders both
human text and `--json`, with a shared graph_state pulse, through
{file_link("src/output.rs")}. The dual-mode contract is what makes loom
scriptable without a separate API.

{link('f2995090-ba95-48d3-bb6d-21b4044c32dc')} — `loom guide`, `loom door`,
`loom complete`, and the orient printout. The teaching axis is a first-class
component, not documentation: it reads the graph and emits the next concrete
invocation.

### Persistence and edges

{link('01783338-7f02-4f4b-8d15-5f396ef7d47d')} — embedded SQLite store in
{file_link("src/db/sqlite.rs")} behind the typed query layer in
{file_link("src/db/queries/")}. Schema vocabulary in Rust; tables and
constraints in SQLite.

{link('c2f6bca0-2ccd-48b7-af47-1a74fba61441')} — the intent that tracks the
migration from the legacy live-graph backend. Proven by the parity harness in
{file_link("tests/sqlite_regression.rs")} and the round-trip checks in
{file_link("src/db/queries/portability.rs")}.

{link('29288a6c-3f0b-4762-a34d-ad4a714b5390')} — every edge kind (RELATES_TO,
HIERARCHY, IMPLEMENTS, GOVERNS, VALIDATES, TARGETS, SERVES, JOURNEYS) is keyed
by endpoint ids with a derived stable edge id, so an edge survives re-import
and is identity-stable. Implemented in {file_link("src/db/schema.rs")} and
{file_link("src/db/queries/")}.

### Work selection and audit

{link('47c9182c-f7a8-4a50-9281-6d05507e646c')} — `loom next --mode <lane>`
ranks the next item for every lane (build, fix, quality, discovery, align,
validate, populate). Scoring in {file_link("src/db/queries/scoring.rs")}.

{link('ab4ac603-a14d-4ae4-b68b-a4bf9dce0cb2')} — `loom doctor`, `loom smells`,
`loom coverage`. The deterministic integrity axis that catches graph/code
drift. Implementations in {file_link("src/commands/doctor.rs")},
{file_link("src/commands/smells.rs")}, {file_link("src/commands/coverage.rs")}.

{link('c61f66f5-a396-4494-9b48-c00d5203bcb3')} — multi-hop graph reads via the
shared snapshot in {file_link("src/db/queries/snapshot.rs")}. Backs
`loom explain`, `loom impact`, and `loom cluster`.

{link('e2d64ed4-b10f-48fd-995b-f533a6250a18')} — `loom find`, `loom smells`,
`loom coverage` share a single read-only snapshot per invocation.
Implementations in {file_link("src/db/queries/stats.rs")} and
{file_link("src/db/queries/scoring.rs")}.

### Sync and analysis

{link('29799603-3704-4dfa-9ba4-387a7c1942f8')} — `loom sync` re-hashes touched
files and flips only one-hop RELATES_TO neighbours to `needs_reverification`,
with a decaying ripple beyond. Implemented in
{file_link("src/commands/sync.rs")} and {file_link("src/repo.rs")}.

{link('382c288a-4846-46f6-93be-eb9e1f40faf3')} — `loom detect` and the
stack/file evidence behind quality-pack recommendations. Implementation in
{file_link("src/repo.rs")}.

{link('ea9c7e3e-9f95-4d58-ade9-d771fcf50cc3')} — multi-language static analysis
(Rust, Go, Dart, Kotlin, Swift, Svelte/Bun) extracting imports, declarations,
and layout signals. Implementations in {file_link("src/ts_imports.rs")} and
language modules under analysis.

{link('dda91659-329a-479e-9d33-42a41b5fa9b1')} — the source corpus that
`loom sync` walks; coverage of which files are registered and which are
untracked. Backed by {file_link("src/repo.rs")}.

### Governance and speculation

{link('20bf582e-df31-4f96-8b37-6171c38e3478')} — the lane gates (builder,
validator, analyst, registrar, reviewer, scout, architect, fixer, quality) and
the evidence requirements behind every transition. Implementations in
{file_link("src/gate.rs")} and {file_link("src/agent.rs")}.

{link('32b42fd0-6b6c-46a6-a9a8-97be595bddf3')} — the pre-decision plane:
improvement hypotheses any lane can propose, an analyzer proves against
current code, and a builder adopts into planned intents. Speculation stays
invisible to coverage until adoption. Implementations in
{file_link("src/commands/hypothesis.rs")} and {file_link("src/db/queries/")}.

{link('fcf2f089-6dbe-46f0-8296-d50512420ff8')} — externally callable surfaces
modelled as first-class graph nodes so ownership, journey coverage, quality
rules, and implementation grounding can address an interface independently of
the saga YAML that calls it. Implementations in
{file_link("src/commands/interface.rs")} and {file_link("src/db/queries/")}.

{link('4c752ad2-e332-4148-87e2-88340991e2a5')} — the saga consumer plane:
`loom saga` validates YAML-defined call sequences against the interface
surface so a journey is provable, not asserted. Implementation in
{file_link("src/commands/saga.rs")}.

### Seed flows

{link('c6b2b5d9-387a-4fa3-936d-e4e780021067')} — the visual-register seed
ladder: reaction-driven, with an HTML mockup as the reaction surface and
contract, mockup-as-CodeFile that never satisfies production IMPLEMENTS, and
machine-first verification with a human visual-confirm queue. Implementation
in {file_link("src/commands/seed.rs")}.

{link('e21d2c64-f9fa-46c0-aaec-1985efbf8152')} — the intent-spectrum seed
guidance that points a driver at the right seed flow for a given intent class.
Implementation in {file_link("src/commands/seed.rs")} and
{file_link("src/commands/guide.rs")}.
"""

PROSE["quality.md"] = f"""\
## The quality axis

The quality axis is how loom certifies *itself*. Every anti-pattern that
matters to this codebase is a named `QualityRule` with a criterion, an
inspection effort, and a recorded verdict per intent it governs. The skeleton
above lists the rules and the verdict bars; the prose below explains the *why*
behind each rule family and how a driver should respond to a finding.

### How quality is certified

A `QualityRule` is seeded from a quality pack (`loom rule seed <pack>`). Each
pack is a vantage point — daemon, sqlite, cli, etc. — chosen because the repo's
disk evidence says it applies. Seeding is never automatic: the agent decides
which packs fit, then `loom detect` recommends and `loom rule seed` installs.
Once a rule is seeded, `loom next --mode quality` surfaces uninspected or stale
GOVERNS pairs; the quality lane records a verdict with confidence and an
evidence locator. A verdict with confidence < 0.7 escalates to the reviewer
lane — the strategic double-check — so the hard calls are never closed by a
single low-confidence read.

The integrity of the quality axis itself is guarded by the
{link('ab4ac603-a14d-4ae4-b68b-a4bf9dce0cb2')}: `loom doctor` audits required
graph properties, `loom smells` surfaces advisory anti-pattern buckets, and
`loom coverage` reports which intents are governed and which are unaccounted.
These three commands are the deterministic checks that catch the quality axis
drifting from the code.

### The lane gates

Every transition in the graph is gated by the
{link('20bf582e-df31-4f96-8b37-6171c38e3478')}: a builder cannot record a
verdict, a validator cannot seed a rule, an analyst cannot ground an intent.
The gates are not advisory — they refuse the write. This is what makes the
graph append-only-auditable: every transition carries the lane and the
evidence, so a later audit can reconstruct *why* the graph looks the way it
does. See [decisions.md](decisions.md) for the recorded rulings that
adjudicate smell findings and lock in non-obvious design choices.

### Work selection under quality

The {link('47c9182c-f7a8-4a50-9281-6d05507e646c')} is shared across every
lane, including quality. `loom next --mode quality` ranks uninspected or stale
GOVERNS pairs by centrality and freshness; the quality lane records a verdict
and the queue drains. The cross-cutting read-side — the
{link('c61f66f5-a396-4494-9b48-c00d5203bcb3')}, the
{link('e2d64ed4-b10f-48fd-995b-f533a6250a18')} — feeds the ranking from a
single loaded snapshot per invocation, so quality work does not pay for
re-scanning the graph.

### Multi-hop audit and the snapshot layer

The {link('c61f66f5-a396-4494-9b48-c00d5203bcb3')} is the read-side that
serves multi-hop graph computations — `loom explain`, `loom impact`,
`loom cluster` — without re-scanning. It is backed by the shared snapshot in
{file_link("src/db/queries/snapshot.rs")}, and the
{link('e2d64ed4-b10f-48fd-995b-f533a6250a18')} reuses that snapshot across
`loom find`, `loom smells`, and `loom coverage` so overlapping bulk reads are
loaded once per command.

### Provenance and the comprehension axis

This wiki page is itself an instance of the quality philosophy: the prose is
falsifiable, not trusted. `loom wiki --okf --prose-check` certifies the
coverage, freshness, and consistency gates; prose quality stays human-gated.
The same principle — mechanical roll-up, human-gated judgment — that governs
the quality axis governs the comprehension axis.
"""

PROSE["glossary.md"] = f"""\
## The vocabulary

The skeleton above lists every vocab term declared in the graph. The prose
below defines the terms that recur across the wiki and explains the
distinctions that matter when reading the other pages. Terms are grouped by
the component that owns them.

### Graph shape

- **Intent** — a named, criteriated, lifecycle-tracked responsibility node.
  Every intent has an abstraction level (system / component / feature / leaf),
  a visibility (internal / user_visible), a lifecycle (planned / implemented /
  deprecated), and a status (proposed / confirmed). The system intent
  {link('6faa01a5-920a-4231-b840-f4c2057d149b')} is the root.
- **CodeFile** — a registered source file with a content-hash. The
  {link('01783338-7f02-4f4b-8d15-5f396ef7d47d')} stores them; the
  {link('29799603-3704-4dfa-9ba4-387a7c1942f8')} re-hashes them on sync.
- **Edge** — a typed relationship between two endpoints. Every edge kind is
  {link('29288a6c-3f0b-4762-a34d-ad4a714b5390')}: keyed by endpoint ids with a
  derived stable edge id, identity-stable across re-import.

### Edges

- **RELATES_TO** — intent-to-intent coupling. The discovery lane ranks
  unexplored pairs; the {link('47c9182c-f7a8-4a50-9281-6d05507e646c')} surfaces
  them.
- **HIERARCHY** — parent/child decomposition. A component intent owns a family
  of feature intents.
- **IMPLEMENTS** — intent-to-codefile grounding with an optional locator (a
  symbol anchor in the file).
- **GOVERNS** — rule-to-intent: a QualityRule governs an intent. The quality
  lane records verdicts on GOVERNS pairs.
- **VALIDATES** — validation-to-intent: a proof object attached to an intent.
- **TARGETS** — hypothesis-to-intent: the speculation plane's edge.
- **SERVES** — interface-to-intent: the {link('fcf2f089-6dbe-46f0-8296-d50512420ff8')}'s edge.
- **JOURNEYS** — saga-to-interface: the {link('4c752ad2-e332-4148-87e2-88340991e2a5')}'s edge.

### Lanes and gates

- **Lane** — a role with write authority over a class of transitions. The
  {link('20bf582e-df31-4f96-8b37-6171c38e3478')} declares the lanes and their
  evidence requirements.
- **Builder** — owns realization: seeding, grounding, realizing intents.
- **Validator** — owns proof: running validations and recording honest results.
- **Analyst** — owns exploration: discovery, smells, edge exploration.
- **Registrar** — owns clerk work: registering codefiles, closing coverage.
- **Reviewer** — owns the strategic double-check: verdicts with confidence <
  0.7 escalate here.

### Quality and proof

- **QualityRule** — a named anti-pattern with a criterion and an inspection
  effort. Seeded from a pack; governs intents.
- **Verdict** — a lane's ruling on a GOVERNS pair, with confidence and an
  evidence locator. Confidence < 0.7 escalates to the reviewer.
- **Validation** — a proof object attached to an intent: a command, an expected
  outcome, and a last result (not_run / passed / failed / blocked).
- **Asserted-only vs executed-proven** — a validation that merely asserts a
  pass vs one that runs and discriminates behaviour. The integrity axis
  ({link('ab4ac603-a14d-4ae4-b68b-a4bf9dce0cb2')}) flags the former.

### Speculation and surfaces

- **Hypothesis** — a pre-decision improvement proposal. The
  {link('32b42fd0-6b6c-46a6-a9a8-97be595bddf3')} is the plane; adoption
  converts a hypothesis into planned intents, never duplicates.
- **Interface surface** — an externally callable surface modelled as a graph
  node, owned by the {link('fcf2f089-6dbe-46f0-8296-d50512420ff8')}.
- **Saga** — a YAML-defined call sequence over interface surfaces, validated by
  the {link('4c752ad2-e332-4148-87e2-88340991e2a5')}.
- **Seed flow** — a reaction-driven realization path for a specific intent
  class. The {link('c6b2b5d9-387a-4fa3-936d-e4e780021067')} is the
  visual-register variant; the
  {link('e21d2c64-f9fa-46c0-aaec-1985efbf8152')} is the guidance that points at
  the right one.

### Sync and analysis

- **sync flag** — the `needs_reverification` / `not_run` flip the
  {link('29799603-3704-4dfa-9ba4-387a7c1942f8')} propagates one hop from a
  changed file's intents, with a decaying ripple beyond.
- **content-hash** — FNV-1a 64-bit hash of file bytes, the change detector's
  truth (mtime alone false-flags after checkout/rebase).
- **corpus** — the source corpus the {link('dda91659-329a-479e-9d33-42a41b5fa9b1')} tracks.
- **static analysis** — the {link('ea9c7e3e-9f95-4d58-ade9-d771fcf50cc3')} plane
  that extracts imports, declarations, and layout signals per language.

### Comprehension

- **OKF** — the Open Knowledge Format: a directory of markdown concept files
  with YAML frontmatter and cross-links. This wiki is an OKF bundle.
- **provenance stamp** — the frontmatter field carrying the content-hashes of
  cited codefiles and the ids of cited intents, so prose freshness is
  mechanically checkable.
- **coverage ledger** — the set of salient intents cited by at least one prose
  page. The coverage gate fails on any uncited salient intent.
"""

PROSE["decisions.md"] = f"""\
## The decision record

The skeleton above lists every `decision` note recorded in the graph. The
prose below explains the *classes* of decision that shape the codebase and
points at the rulings that lock them in. Decisions are how loom adjudicates
smell findings and locks in non-obvious design choices; they are the
human-gated counterpart to the mechanical gates.

### Why decisions exist

A smell finding is advisory, not a defect. When a smell is acceptable — a
panic marker that is actually an invariant, a string duplicate that is a DDL
idiom — the right response is not to refactor, it is to record a `decision`
note that adjudicates the finding and carries the reasoning. The
{link('ab4ac603-a14d-4ae4-b68b-a4bf9dce0cb2')} then moves the finding out of
the open advisory count into the adjudicated output, with a reopen anchor on
the relevant intent or file. This is why `loom smells` distinguishes open from
adjudicated: a green smell axis is not "no smells", it is "every smell is
either fixed or adjudicated".

### Decision classes in this repo

The recurring decision classes, each backed by recorded rulings in the
skeleton above:

- **Panic-marker-as-invariant** — `unwrap` / `expect` calls that encode a
  genuine invariant (e.g. serializing a JSON error object that cannot fail).
  The decision records the invariant and reopens if the invariant ever breaks.
- **DDL-idiom-string-duplicate** — repeated `TEXT NOT NULL DEFAULT ''` across
  SQLite schema DDL. The duplicate is the idiom, not a debt; the decision
  records that the schema file is co-located and the duplication is intentional.
- **Co-located-UX-duplicate** — strings that recur across CLI subcommands
  because the UX contract is co-located. The decision records the UX contract.
- **Backend-retirement** — the retired `loom serve` stub. The decision records
  that the {link('01783338-7f02-4f4b-8d15-5f396ef7d47d')} made it obsolete and
  the command refuses with a teaching message rather than silently disappearing.

### How a decision is recorded

`loom note add --intent <id> --kind decision --body "<ruling and reasoning>"`
records a decision. The note's `kind` is `decision`; the body carries the
ruling and the reasoning; the note is linked to the intent (or file) it
adjudicates. The {link('20bf582e-df31-4f96-8b37-6171c38e3478')} gates who can
record a decision — only the reviewer lane closes a smell with a decision, so
the strategic double-check is the one that adjudicates.

### Decisions and the comprehension axis

This page is itself decision-shaped: the prose is the human-gated layer, the
skeleton is the mechanical layer, and the decisions recorded above are the
bridge. A reader who wants to know *why* the code looks the way it does reads
this page; a reader who wants to know *what* the code does reads
[components.md](components.md); a reader who wants to know *how a request
travels* reads [flows.md](flows.md).
"""

PROSE["flows.md"] = f"""\
## How a request travels

This page traces a representative `loom` invocation end-to-end, naming every
component intent it touches. The skeleton above lists the journey coverage
from the saga plane; the prose below is the narrative that ties the components
into a single path.

### Flow 1 — `loom next --mode build` (the work-selection path)

1. **Resolve the graph.** `loom` resolves the target graph via `--graph` flag
   > `LOOM_GRAPH` env > cwd, through `resolve_root()` in
   {file_link("src/db/mod.rs")}. This is the graph-targeting pin that prevents
   the cd-fallback incident class.
2. **Dispatch.** The {link('a1a8eb10-bc4c-43d7-a4ec-b7d1fb8d26ae')} parses the
   args and the dispatch table in {file_link("src/commands/mod.rs")} routes
   `next` to {file_link("src/commands/next.rs")}.
3. **Load the snapshot.** The handler opens the SQLite store via
   {file_link("src/db/sqlite.rs")} and loads a single shared snapshot through
   the {link('e2d64ed4-b10f-48fd-995b-f533a6250a18')} — the same snapshot that
   `loom smells` and `loom coverage` would use, loaded once.
4. **Rank.** The {link('47c9182c-f7a8-4a50-9281-6d05507e646c')} scores every
   build-eligible intent via {file_link("src/db/queries/scoring.rs")} and
   returns the top item with its lane, evidence requirements, and the exact
   next invocation.
5. **Render.** The {link('bb8ee237-2d84-46ee-b254-c8bc39c16fc1')} renders the
   item as human text (default) or `--json` (for scripting), with the
   graph_state pulse, through {file_link("src/output.rs")}.

### Flow 2 — `loom sync` (the change-detection path)

1. **Resolve + dispatch** as above, routing to {file_link("src/commands/sync.rs")}.
2. **Re-hash.** The {link('29799603-3704-4dfa-9ba4-387a7c1942f8')} re-hashes
   every file under the corpus using the FNV-1a content-hash in
   {file_link("src/repo.rs")}. A changed hash (not a changed mtime) is the
   trigger — mtime alone false-flags after checkout/rebase.
3. **Propagate.** For each changed file's intents, the one-hop RELATES_TO
   neighbours flip to `needs_reverification`; passing GOVERNS go
   `needs_reverification`; linked validations go `not_run`. Two- and three-hop
   neighbours receive a decaying priority bump that does not change their
   inspection_status.
4. **Report.** Files missing on disk are reported; the
   {link('ab4ac603-a14d-4ae4-b68b-a4bf9dce0cb2')} is the axis that catches a
   graph drifting from the code.

### Flow 3 — `loom wiki --okf --prose-check` (the comprehension path)

1. **Resolve + dispatch** as above, routing to {file_link("src/commands/wiki.rs")}.
2. **Load.** The handler loads the snapshot and renders the deterministic
   skeleton pages (the byte-checked frame).
3. **Extract prose.** For each page, the prose between the
   `<!-- loom:prose-start -->` and `<!-- loom:prose-end -->` sentinels is
   extracted.
4. **Run the three gates.** Coverage: every salient intent (system / component
   / user_visible, non-deprecated) is cited by at least one page. Freshness:
   every cited codefile's on-disk content-hash matches the registered hash.
   Consistency: every cross-link resolves to a real graph node. Prose quality
   is human-gated and intentionally NOT certified here.
5. **Report.** Findings are printed one per line with a remedy; the command
   exits non-zero on any finding. A green `--prose-check` means the
   comprehension axis is mechanically green; the human-gated prose-quality
   queue is the remaining gate.

### Flow 4 — a hypothesis adoption (the speculation path)

1. **Propose.** Any lane records a hypothesis via `loom hypothesis add` — a
   claim, a proposal, and a falsifiable predicted_outcome. The
   {link('32b42fd0-6b6c-46a6-a9a8-97be595bddf3')} is the plane; the hypothesis
   is invisible to coverage and completeness.
2. **Prove.** An analyzer (not the proposer) runs `loom hypothesis prove`
   against current code. The prover's provenance must differ from the
   proposer's; a supported hypothesis has the evidence to back its
   predicted_outcome.
3. **Adopt.** A builder runs `loom hypothesis adopt`. The
   {link('20bf582e-df31-4f96-8b37-6171c38e3478')} gates the adoption: the
   predicted_outcome is written as a `not_run` Validation attached to the
   spawned intents, so the validator lane later checks whether the improvement
   actually delivered. The hypothesis itself never enters build queues,
   coverage axes, or completeness — adoption hands all real work to the
   existing intent machinery.

### Flow 5 — a saga validation (the journey path)

1. **Define.** A saga YAML names a sequence of calls over
   {link('fcf2f089-6dbe-46f0-8296-d50512420ff8')} nodes — the externally
   callable surfaces modelled as first-class graph nodes.
2. **Validate.** The {link('4c752ad2-e332-4148-87e2-88340991e2a5')} validates
   the sequence against the interface surface: every call resolves, every
   step's pre/post conditions are checkable, and the journey is provable, not
   asserted.
3. **Report.** A failing saga is a journey-coverage finding, surfaced by the
   {link('ab4ac603-a14d-4ae4-b68b-a4bf9dce0cb2')}.
"""


def inject_prose(path, prose):
    with open(path, "r") as f:
        content = f.read()
    start_idx = content.find(PROSE_START)
    end_idx = content.find(PROSE_END)
    if start_idx == -1 or end_idx == -1 or end_idx < start_idx:
        raise SystemExit(f"sentinels not found in {path}")
    after_start = start_idx + len(PROSE_START)
    if content[after_start:after_start + 1] == "\n":
        after_start += 1
    new_content = content[:after_start] + prose + "\n" + content[end_idx:]
    with open(path, "w") as f:
        f.write(new_content)


def main():
    for name, prose in PROSE.items():
        path = os.path.join(WIKI, name)
        if not os.path.exists(path):
            raise SystemExit(f"missing {path} - run `loom wiki --okf` first")
        inject_prose(path, prose)
        print(f"  + authored prose on {name}")
    print(f"\nAuthored prose on {len(PROSE)} pages. Run `loom wiki --okf --prose-check` to certify.")


if __name__ == "__main__":
    main()
